FROM golang:1.18-alpine

RUN apk update
RUN apk add build-base
RUN apk add git

WORKDIR /srclient
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY *.go ./

CMD ["go", "test", "-tags", "integration", "."]