name: srclient Main Workflow
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download dependencies
        run: go mod download
      - name: Run unit tests
        run: go test -cover -v ./...
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run containerized integration tests
        run: docker compose up --exit-code-from srclient-integration-test